"""Order 013-m, M1: focused tests for the frozen runtime lock closure gate.

The Dockerfile runtime stage must install the ACTUAL frozen lock closure
into /opt/slaif/venv (no second dependency resolution) and the in-image
provenance gate must compare the actually installed distributions against
the build-stage export of the committed uv.lock. Missing, wrong-version,
or unexpected runtime dependencies must FAIL the gate; the in-image audit
script must embed the exact tested function sources; the Dockerfile must
carry the explicit frozen-sync target and the --no-deps wheel install.

No Docker, no network: pure functions, generated audit code, and the
committed Dockerfile bytes only.
"""

from __future__ import annotations

import importlib.util
import inspect
import sys
import types
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]
QUAL_SCRIPT = REPO_ROOT / "scripts" / "docker_qualification_ci.py"
DOCKERFILE = REPO_ROOT / "Dockerfile"

# Deterministic Linux amd64 / CPython 3.12 environment facts (the supported
# image platform) for marker-evaluation tests.
LINUX_AMD64_PY312_ENV = {
    "sys_platform": "linux",
    "os_name": "posix",
    "platform_system": "Linux",
    "platform_machine": "x86_64",
    "platform_release": "6.1.0-18",
    "platform_version": "#1 SMP",
    "python_version": "3.12",
    "python_full_version": "3.12.14",
    "implementation_name": "cpython",
}


def _load_module(path: Path, name: str) -> types.ModuleType:
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load {name}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


@pytest.fixture(scope="module")
def dqc() -> types.ModuleType:
    return _load_module(QUAL_SCRIPT, "docker_qualification_ci_for_closure_tests")


# ---------------------------------------------------------------------------
# PEP 503 canonical names
# ---------------------------------------------------------------------------


class TestCanonicalName:
    def test_underscore_and_case(self, dqc: types.ModuleType) -> None:
        assert dqc._slaif_canonical_name("pydantic_core") == "pydantic-core"
        assert dqc._slaif_canonical_name("Pydantic-Core") == "pydantic-core"
        assert dqc._slaif_canonical_name("prometheus_client") == "prometheus-client"

    def test_dot_and_runs(self, dqc: types.ModuleType) -> None:
        assert dqc._slaif_canonical_name("zope.interface") == "zope-interface"
        assert dqc._slaif_canonical_name("a__b..c-d.e") == "a-b-c-d-e"


# ---------------------------------------------------------------------------
# Frozen pin parsing (uv export output)
# ---------------------------------------------------------------------------


class TestParseFrozenPins:
    def test_plain_pins_and_marker(self, dqc: types.ModuleType) -> None:
        text = (
            "# This file was autogenerated by uv via the following command:\n"
            "anyio==4.14.2\n"
            "certifi==2026.7.22\n"
            "colorama==0.4.6 ; sys_platform == 'win32'\n"
            "\n"
        )
        pins = dqc._slaif_parse_frozen_pins(text)
        assert pins == {
            "anyio": ("4.14.2", None),
            "certifi": ("2026.7.22", None),
            "colorama": ("0.4.6", "sys_platform == 'win32'"),
        }

    def test_comments_and_blanks_skipped(self, dqc: types.ModuleType) -> None:
        pins = dqc._slaif_parse_frozen_pins("# only a comment\n\nfastapi==0.141.1\n")
        assert pins == {"fastapi": ("0.141.1", None)}

    @pytest.mark.parametrize(
        "line",
        [
            "anyio",  # no version
            "anyio==",  # empty version
            "==4.14.2",  # no name
            "anyio==4.14.2 ; ",  # empty marker
            "anyio @ https://example.com/anyio.whl",  # URL form
            "anyio[extra]==4.14.2",  # extras are not in a lock export
            "--no-index",  # option lines
            "-r requirements.txt",  # option lines
        ],
    )
    def test_malformed_lines_rejected(self, dqc: types.ModuleType, line: str) -> None:
        with pytest.raises(ValueError):
            dqc._slaif_parse_frozen_pins(line + "\n")

    def test_duplicate_name_rejected(self, dqc: types.ModuleType) -> None:
        with pytest.raises(ValueError):
            dqc._slaif_parse_frozen_pins("anyio==4.14.2\nanyio==4.15.1\n")

    def test_empty_file_rejected(self, dqc: types.ModuleType) -> None:
        with pytest.raises(ValueError):
            dqc._slaif_parse_frozen_pins("")
        with pytest.raises(ValueError):
            dqc._slaif_parse_frozen_pins("# only comments\n\n")


# ---------------------------------------------------------------------------
# Closed-grammar PEP 508 marker evaluation (fail-closed)
# ---------------------------------------------------------------------------


class TestMarkerApplies:
    env = LINUX_AMD64_PY312_ENV

    def test_win32_marker_false_on_supported_platform(self, dqc: types.ModuleType) -> None:
        assert dqc._slaif_marker_applies("sys_platform == 'win32'", self.env) is False

    def test_linux_marker_true_on_supported_platform(self, dqc: types.ModuleType) -> None:
        assert dqc._slaif_marker_applies("sys_platform == 'linux'", self.env) is True

    def test_version_comparisons(self, dqc: types.ModuleType) -> None:
        assert dqc._slaif_marker_applies("python_version == '3.12'", self.env) is True
        assert dqc._slaif_marker_applies("python_version >= '3.11'", self.env) is True
        assert dqc._slaif_marker_applies("python_version >= '3.13'", self.env) is False
        assert dqc._slaif_marker_applies("python_version < '3.13'", self.env) is True
        # PEP 508 also allows unquoted version literals.
        assert dqc._slaif_marker_applies("python_version == 3.12", self.env) is True
        assert dqc._slaif_marker_applies("python_version >= 3.11", self.env) is True

    def test_version_tuple_zero_padding(self, dqc: types.ModuleType) -> None:
        # (3,12,14) vs (3,12): equal only after zero-padding the shorter
        # release for ORDERING, never for == (3.12.14 != 3.12).
        assert dqc._slaif_marker_applies("python_full_version == '3.12.14'", self.env) is True
        assert dqc._slaif_marker_applies("python_full_version == '3.12'", self.env) is False
        assert dqc._slaif_marker_applies("python_full_version >= '3.12'", self.env) is True
        assert dqc._slaif_marker_applies("python_full_version >= '3.12.15'", self.env) is False

    def test_and_joined_clauses(self, dqc: types.ModuleType) -> None:
        ok = dqc._slaif_marker_applies(
            "sys_platform == 'linux' and python_version >= '3.12'", self.env
        )
        assert ok is True
        bad = dqc._slaif_marker_applies(
            "sys_platform == 'linux' and python_version >= '3.13'", self.env
        )
        assert bad is False

    def test_real_interpreter_env_matches_sys_platform(self, dqc: types.ModuleType) -> None:
        # env=None builds the facts from the RUNNING interpreter (the
        # in-image call path); the result must equal the direct comparison.
        assert dqc._slaif_marker_applies("sys_platform == 'win32'") is (sys.platform == "win32")

    @pytest.mark.parametrize(
        "marker",
        [
            "sys_platform in 'linux'",  # in-operator: outside the closed grammar
            "not sys_platform == 'linux'",  # negation: outside the closed grammar
            "extra == 'x'",  # unknown variable
            "sys_platform == 'linux' or python_version == '3.12'",  # or: outside the grammar
        ],
    )
    def test_outside_closed_grammar_fails_closed(self, dqc: types.ModuleType, marker: str) -> None:
        with pytest.raises(ValueError):
            dqc._slaif_marker_applies(marker, self.env)


# ---------------------------------------------------------------------------
# Closure evaluation: positive and every required negative case (M1)
# ---------------------------------------------------------------------------


class TestEvaluateRuntimeClosure:
    PINS: dict[str, tuple[str, str | None]] = {
        "anyio": ("4.14.2", None),
        "pydantic": ("2.13.4", None),
        "colorama": ("0.4.6", "sys_platform == 'win32'"),
    }

    def _installed(self, **overrides: str) -> dict[str, str]:
        base = {
            "anyio": "4.14.2",
            "pydantic": "2.13.4",
            "slaif-local-coding": "0.1.0",
        }
        base.update(overrides)
        return base

    def test_exact_closure_passes(self, dqc: types.ModuleType) -> None:
        result = dqc._slaif_evaluate_runtime_closure(
            self.PINS, self._installed(), "slaif-local-coding", "0.1.0"
        )
        assert result["ok"] is True
        assert result["missing"] == {}
        assert result["wrong_version"] == {}
        assert result["unexpected"] == {}
        assert result["product_ok"] is True
        assert result["pinned_count"] == 3
        assert result["applicable_count"] == 2  # colorama not applicable here
        assert result["installed_count"] == 3
        assert result["installed"] == self._installed()

    def test_missing_dependency_fails(self, dqc: types.ModuleType) -> None:
        installed = self._installed()
        del installed["pydantic"]
        result = dqc._slaif_evaluate_runtime_closure(
            self.PINS, installed, "slaif-local-coding", "0.1.0"
        )
        assert result["ok"] is False
        assert result["missing"] == {"pydantic": "2.13.4"}

    def test_wrong_version_fails(self, dqc: types.ModuleType) -> None:
        # The exact drift the defect produced: the wheel install re-resolved
        # anyio to a newer version than the frozen lock.
        result = dqc._slaif_evaluate_runtime_closure(
            self.PINS, self._installed(**{"anyio": "4.15.1"}), "slaif-local-coding", "0.1.0"
        )
        assert result["ok"] is False
        assert result["wrong_version"] == {"anyio": {"installed": "4.15.1", "expected": "4.14.2"}}

    def test_unexpected_distribution_fails(self, dqc: types.ModuleType) -> None:
        result = dqc._slaif_evaluate_runtime_closure(
            self.PINS,
            self._installed(**{"requests": "2.32.0"}),
            "slaif-local-coding",
            "0.1.0",
        )
        assert result["ok"] is False
        assert result["unexpected"] == {"requests": "2.32.0"}

    def test_inapplicable_marker_dependency_installed_fails(self, dqc: types.ModuleType) -> None:
        # colorama is locked only for win32; on the supported platform it
        # must be ABSENT — a present colorama means the environment was
        # built by a different (second) resolution.
        result = dqc._slaif_evaluate_runtime_closure(
            self.PINS,
            self._installed(**{"colorama": "0.4.6"}),
            "slaif-local-coding",
            "0.1.0",
        )
        assert result["ok"] is False
        assert result["unexpected"] == {"colorama": "0.4.6"}

    def test_inapplicable_marker_dependency_absent_passes(self, dqc: types.ModuleType) -> None:
        result = dqc._slaif_evaluate_runtime_closure(
            self.PINS, self._installed(), "slaif-local-coding", "0.1.0"
        )
        assert result["ok"] is True

    def test_product_wheel_missing_fails(self, dqc: types.ModuleType) -> None:
        installed = self._installed()
        del installed["slaif-local-coding"]
        result = dqc._slaif_evaluate_runtime_closure(
            self.PINS, installed, "slaif-local-coding", "0.1.0"
        )
        assert result["ok"] is False
        assert result["product_ok"] is False

    def test_product_wheel_wrong_version_fails(self, dqc: types.ModuleType) -> None:
        result = dqc._slaif_evaluate_runtime_closure(
            self.PINS,
            self._installed(**{"slaif-local-coding": "9.9.9"}),
            "slaif-local-coding",
            "0.1.0",
        )
        assert result["ok"] is False
        assert result["product_ok"] is False

    def test_unsupported_marker_fails_closed(self, dqc: types.ModuleType) -> None:
        pins = {"anyio": ("4.14.2", "extra == 'x'")}
        with pytest.raises(ValueError):
            dqc._slaif_evaluate_runtime_closure(
                pins, self._installed(), "slaif-local-coding", "0.1.0"
            )


# ---------------------------------------------------------------------------
# The in-image audit code (single source of truth + driver contract)
# ---------------------------------------------------------------------------


class TestInImageAuditCode:
    def test_compiles(self, dqc: types.ModuleType) -> None:
        code = dqc._runtime_venv_audit_code()
        compile(code, "<in-image-audit>", "exec")

    def test_embeds_exact_tested_function_sources(self, dqc: types.ModuleType) -> None:
        code = dqc._runtime_venv_audit_code()
        for fn in (
            dqc._slaif_canonical_name,
            dqc._slaif_parse_frozen_pins,
            dqc._slaif_marker_applies,
            dqc._slaif_evaluate_runtime_closure,
        ):
            assert inspect.getsource(fn) in code, f"source of {fn.__name__} not embedded"

    def test_driver_contract(self, dqc: types.ModuleType) -> None:
        code = dqc._runtime_venv_audit_code()
        # Existing checks preserved.
        assert 'md.distribution("slaif-local-coding")' in code
        assert 'assert dist.version == "0.1.0", dist.version' in code
        assert '"/site-packages/slaif_local_coding/" in loc' in code
        assert "hashlib.sha256(open(wheel, " in code
        # M1 closure inspection of the actually installed distributions.
        assert dqc.FROZEN_RUNTIME_CLOSURE_PATH in code
        assert "_slaif_parse_frozen_pins(pins_text)" in code
        assert "_slaif_evaluate_runtime_closure(pins, installed, " in code
        assert "md.distributions()" in code
        assert "raise SystemExit(1)" in code
        # Bounded JSON out, no secrets, no raw payloads.
        assert "json.dumps" in code


# ---------------------------------------------------------------------------
# Dockerfile wiring (the mechanical M1 fix, proven from the committed bytes)
# ---------------------------------------------------------------------------


class TestDockerfileRuntimeLockWiring:
    @pytest.fixture(scope="class")
    def dockerfile(self) -> str:
        return DOCKERFILE.read_text(encoding="utf-8")

    def test_build_stage_exports_frozen_closure_from_lock(self, dockerfile: str) -> None:
        assert "RUN uv export --frozen --no-dev --no-emit-project --no-hashes" in dockerfile
        assert "/build/wheel/requirements-runtime-frozen.txt" in dockerfile

    def test_runtime_sync_targets_the_explicit_venv(self, dockerfile: str) -> None:
        # --active syncs the environment named by VIRTUAL_ENV; a plain
        # `uv sync` would create and fill the project .venv instead (the
        # demonstrated defect).
        assert (
            "VIRTUAL_ENV=/opt/slaif/venv uv sync --frozen --no-dev --no-install-project --active"
            in dockerfile
        )

    def test_closure_file_copied_into_runtime_image(self, dockerfile: str) -> None:
        assert (
            "COPY --from=build /build/wheel/requirements-runtime-frozen.txt /opt/slaif/artifacts/"
            in dockerfile
        )

    def test_wheel_install_has_no_second_resolution(self, dockerfile: str) -> None:
        assert "uv pip install --python /opt/slaif/venv/bin/python --no-deps" in dockerfile

    def test_base_pins_unchanged(self, dockerfile: str) -> None:
        # Order: preserve base digests, build pins, and the stage set.
        python_base = (
            "FROM python:3.12-slim-bookworm@sha256:782412e85d0f0984994c290652577d4018"
            "aff08145c85b262bb63dc0c7522254"
        )
        uv_base = (
            "FROM ghcr.io/astral-sh/uv:0.12.5@sha256:e85be844203885286c60ffad8a858d4"
            "8afb6c5a5c237ca0e67f12e74b8f174b1"
        )
        assert python_base in dockerfile
        assert uv_base in dockerfile
        for stage in ("AS uv-provider", "AS build", "AS runtime"):
            assert stage in dockerfile
