"""Release/deployment provenance manifest generator (order 009-a, workstream E).

Produces a content-free, machine-readable, schema-versioned provenance
manifest for the release candidate. "Content-free" means the manifest carries
only hashes, versions, counts, and fixed status facts — never host paths,
credentials, provider keys, private identifiers, prompts, model output, or raw
acceptance payloads (enforced by the forbidden-content scan shared with the
artifact policy check and by tests/test_release_provenance_manifest.py).

The manifest is generated from actual build inputs (git HEAD, the locked
files, the built artifacts, the deployment templates, and the current Gateway
peer fixture) and is committed under packaging/. The E3 test regenerates it
and fails on any drift or forbidden content.

Usage:

    python scripts/release_provenance_manifest.py --emit packaging/release_provenance_manifest.json
"""

from __future__ import annotations

import argparse
import hashlib
import json
import platform
import re
import subprocess
import sys
import tomllib
from pathlib import Path

SCHEMA_NAME = "slaif-release-provenance-v2"
SCHEMA_VERSION = 2
OBJECTIVE = "012-a"
REPOSITORY = "ulfe-lmi/slaif-local-coding"
GATEWAY_PEER_FIXTURE = Path("tests/fixtures/gateway/current_peer_authority.json")
PACKAGE_NAME = "slaif-local-coding"
CODIX_CLIENT_VERSION = "0.149.0"
CODIX_WIRE_FIXTURE_DIR = "tests/fixtures/codex/0.149.0"

LIMITATIONS: list[str] = [
    "two supported deployment paths: Docker (canonical MVP installation path) "
    "and systemd user service on the local host (secondary direct-host path, "
    "including the protected-host cutover path)",
    "Docker qualified in CI and disposable environments only; "
    "deployment-qualified (disposable/CI environments only), not "
    "release-qualified",
    "LAN-visible binding law in force (D1): a non-loopback adapter bind is "
    "legal only under the full signed ingress contract "
    "(service_bearer_signed_identity_v1); loopback remains the default",
    "cutover not performed",
    "not released; no registry publication, tag, or release state change",
    "OCI image not published (oci.image_digest null, oci.published false); the "
    "container publication path is documented (workflow_dispatch-only, inert) "
    "and not executed",
    "sdist is a developer-only source archive, not a supported release artifact",
    "no multi-user, production-certification, compliance, or frontier-equivalence claim",
    "single RTX 3090 fixture evidence is fixture-scoped, not generic production equivalence",
    "artifacts and OCI build inputs regenerated by objective 011-a after the "
    "runtime package bytes changed (D1 binding-law validator) and the Docker "
    "product surface was added; the objective-010-a wheel hash "
    "8678e16b41bd9d73849a956c9d1f25235532eaf52c772fc695718b2063b54472 remains "
    "the accepted 010 record only, not the cutover authority",
]

TAG_CONVENTION = (
    "0.1.0-<short-sha> (and full-sha form) locally; reserved publication "
    "reference ghcr.io/ulfe-lmi/slaif-local-coding with tags 0.1.0 + "
    "sha-<full-sha> after a human-authorized release"
)
TOPOLOGY_MODE_LABEL = (
    "linux-docker-host-network;loopback-default;lan-visible-only-with-full-signed-ingress"
)
QUALIFICATION_LABEL = "disposable-qualification-only; not released"


def _sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _artifact_facts(path: Path, kind: str) -> dict:
    import tarfile
    import zipfile

    if kind == "wheel":
        with zipfile.ZipFile(path) as wheel:
            entries = [i.filename for i in wheel.infolist() if not i.is_dir()]
    else:
        with tarfile.open(path, "r:gz") as sdist:
            entries = []
            for member in sdist.getmembers():
                if member.isfile():
                    entries.append(member.name)
    return {
        "name": path.name,
        "sha256": _sha256_file(path),
        "size_bytes": path.stat().st_size,
        "entry_count": len(entries),
    }


def _dockerfile_base_images(root: Path) -> tuple[dict, dict]:
    """Return (build_base_image, base_image) parsed from the Dockerfile.

    All three FROM lines must be digest-pinned (B1); any unpinned base is
    a generation failure, never a warning.
    """
    dockerfile = (root / "Dockerfile").read_text(encoding="utf-8")
    found: dict[str, dict] = {}
    for line in dockerfile.splitlines():
        m = re.match(r"^FROM\s+(\S+?)@sha256:([0-9a-f]{64})\s+AS\s+([A-Za-z0-9_-]+)\s*$", line)
        if m:
            found[m.group(3)] = {
                "name": m.group(1),
                "digest": "sha256:" + m.group(2),
            }
    if set(found) != {"uv-provider", "build", "runtime"}:
        raise RuntimeError(
            "Dockerfile must pin exactly the uv-provider, build, and runtime "
            f"images by digest; found: {sorted(found)}"
        )
    return found["uv-provider"], found["build"], found["runtime"]


def _git_commit(root: Path) -> str:
    out = (
        subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=root,
            capture_output=True,
            check=True,
        )
        .stdout.decode()
        .strip()
    )
    if not re.fullmatch(r"[0-9a-f]{40}", out):
        raise RuntimeError("git rev-parse HEAD did not return a 40-hex SHA")
    return out


def build_manifest(repo: Path, dist_dir: Path) -> dict:
    with (repo / "pyproject.toml").open("rb") as stream:
        pyproject = tomllib.load(stream)
    package_version = pyproject["project"]["version"]

    peer = json.loads((repo / GATEWAY_PEER_FIXTURE).read_text(encoding="utf-8"))

    wheels = sorted(
        set(dist_dir.glob(f"{PACKAGE_NAME.replace('-', '_')}-*.whl"))
        | set(dist_dir.glob(f"{PACKAGE_NAME}-*.whl"))
    )
    sdists = sorted(
        set(dist_dir.glob(f"{PACKAGE_NAME.replace('-', '_')}-*.tar.gz"))
        | set(dist_dir.glob(f"{PACKAGE_NAME}-*.tar.gz"))
    )
    if len(wheels) != 1 or len(sdists) != 1:
        raise RuntimeError("expected exactly one wheel and one sdist in dist dir")

    python_version = platform.python_version()
    major_minor = ".".join(python_version.split(".")[:2])

    manifest = {
        "schema": SCHEMA_NAME,
        "schema_version": SCHEMA_VERSION,
        "objective": OBJECTIVE,
        "generated_from": {
            "repository": REPOSITORY,
            "git_commit": _git_commit(repo),
        },
        "gateway_peer": {
            "repository": peer["repository"],
            "commit": peer["commit"],
            "server_module": {
                "module_id": peer["server"]["module_id"],
                "module_version": peer["server"]["module_version"],
                "replay_mode": peer["server"]["replay_mode"],
            },
            "client_module": {
                "module_id": peer["client"]["module_id"],
                "module_version": peer["client"]["module_version"],
            },
        },
        "runtime": {
            "python": major_minor,
            "package_name": PACKAGE_NAME,
            "package_version": package_version,
            "uv_lock_sha256": _sha256_file(repo / "uv.lock"),
            "pyproject_sha256": _sha256_file(repo / "pyproject.toml"),
        },
        "artifacts": {
            "wheel": _artifact_facts(wheels[0], "wheel"),
            "sdist": _artifact_facts(sdists[0], "sdist"),
        },
        "oci": {},  # filled below once the wheel hash is known
        "templates": {
            "config_example_sha256": _sha256_file(repo / "config/adapter.example.toml"),
            "deployment_config_template_sha256": _sha256_file(
                repo / "config/adapter.deployment.template.toml"
            ),
            "gateway_integrated_config_template_sha256": _sha256_file(
                repo / "config/adapter.gateway-integrated.template.toml"
            ),
            "service_unit_sha256": _sha256_file(repo / "packaging/slaif-local-coding.service"),
            "service_unit_example_sha256": _sha256_file(
                repo / "packaging/slaif-local-coding.service.example"
            ),
            "readyz_wait_sha256": _sha256_file(repo / "packaging/readyz-wait.sh"),
        },
        "reference_compatibility": {
            "model_name": "qwen3.8-27b",
            "upstream_interface": "vllm-openai-compat-v1",
            "codex_client": {
                "version": CODIX_CLIENT_VERSION,
                "wire_fixture_dir": CODIX_WIRE_FIXTURE_DIR,
            },
        },
        "status": {
            "deployment_qualified": "disposable-environment-only",
            "cutover_performed": False,
            "released": False,
        },
        "limitations": list(LIMITATIONS),
    }

    build_tool_image, build_base_image, base_image = _dockerfile_base_images(repo)
    manifest["oci"] = {
        "image_reference": "ghcr.io/ulfe-lmi/slaif-local-coding",
        "tag_convention": TAG_CONVENTION,
        "base_image": base_image,
        "build_base_image": build_base_image,
        "build_tool_image": build_tool_image,
        "dockerfile_sha256": _sha256_file(repo / "Dockerfile"),
        "compose_sha256": _sha256_file(repo / "compose.yaml"),
        "dockerignore_sha256": _sha256_file(repo / ".dockerignore"),
        "wheel_sha256": manifest["artifacts"]["wheel"]["sha256"],
        "image_digest": None,
        "published": False,
        "labels": {
            "org.opencontainers.image.source": ("https://github.com/ulfe-lmi/slaif-local-coding"),
            "org.opencontainers.image.version": package_version,
            "slaif-local-coding.package.version": package_version,
            "slaif-local-coding.gateway.peer.sha": manifest["gateway_peer"]["commit"],
            "slaif-local-coding.topology.mode": TOPOLOGY_MODE_LABEL,
            "slaif-local-coding.qualification": QUALIFICATION_LABEL,
            "slaif-local-coding.wheel.sha256": manifest["artifacts"]["wheel"]["sha256"],
        },
    }
    return manifest


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--emit",
        type=Path,
        default=Path("packaging/release_provenance_manifest.json"),
    )
    parser.add_argument("--dist", type=Path, default=Path("dist"))
    args = parser.parse_args()

    repo = Path(__file__).resolve().parents[1]
    manifest = build_manifest(repo, args.dist.resolve())
    payload = json.dumps(manifest, indent=2, sort_keys=True) + "\n"
    args.emit.parent.mkdir(parents=True, exist_ok=True)
    args.emit.write_text(payload, encoding="utf-8")
    print(f"wrote {args.emit} ({len(payload)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
